version: "3"
services:
  app:
    build: .
    container_name: auth-service
    user: root
    entrypoint: /app/entrypoint.sh
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: Authentication
    depends_on:
      - redis
      - postgres
    ports:
      - "8000:8000"
  redis:
    image: redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres
    volumes: 
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Authentication